### ISSUE TITLE
Uncaught Error saving screenshot

### ISSUE THREAD

**Issue by punjabirocker** [webdriverio/webdrivercss#144]
I am trying out one of the examples from the readme to see webdrivercss in action  
describe('when page load', function () {
        it('should display right title', function (done) {
            client
              .url('http://tumblr.com/themes')
              .webdrivercss('tumblrpage', {
                  name: 'startpage',
                  ignore: 'antialiasing',
                  screenWidth: [1200]
              });
        });
    });

my package.json 
"dependencies": {
    "chai": "^3.5.0",
    "mocha": "^2.4.5",
    "webdrivercss": "^1.1.10",
    "webdriverio": "^2.4.5"
  }

it runs through the scenario in browser and while trying to save file it throws with the following stack trace
     ### Uncaught Error: [webdrivercss("tumblrpage",{"name":"startpage","ignore":"antialiasing","screenWidth":[1200]})] <=
 [saveDocumentScreenshot("webdrivercss/tumblrpage.1200px.png")] <=
 write EPIPE
      at exports._errnoException (util.js:856:11)
      at Socket._writeGeneric (net.js:675:26)
      at Socket._write (net.js:694:8)
      at doWrite (_stream_writable.js:292:12)
      at writeOrBuffer (_stream_writable.js:278:5)
      at Socket.Writable.write (_stream_writable.js:207:11)
      at Socket.write (net.js:620:40)
      at gm._spawn (D:\Tools\webdrivercsstemp\node_modules\gm\lib\command.js:241:18)
      at D:\Tools\webdrivercsstemp\node_modules\gm\lib\command.js:101:12
      at series (D:\Tools\webdrivercsstemp\node_modules\array-series\index.js:11:36)
      at gm._preprocess (D:\Tools\webdrivercsstemp\node_modules\gm\lib\command.js:177:5)
      at gm.write (D:\Tools\webdrivercsstemp\node_modules\gm\lib\command.js:99:10)
      at D:\Tools\webdrivercsstemp\node_modules\webdrivercss\lib\documentScreenshot.js:171:35
      at fn (D:\Tools\webdrivercsstemp\node_modules\async\lib\async.js:638:34)
      at Immediate._onImmediate (D:\Tools\webdrivercsstemp\node_modules\async\lib\async.js:554:34)

**Comment by punjabirocker** [comment]
realized that GraphicsMagick installer didn't set the executable PATH.
