### ISSUE TITLE
webdrivercss doesnt work ! 

### ISSUE THREAD

**Issue by SerkanSipahi** [webdriverio/webdrivercss#54]
System
=========
OS: Ubunbu 14.04.1
Nodejs: 0.10.25
webdrivercss: 1.0.6
webdriverio: 2.4.5

issue
========
We cant use webdrivercss because see below error message and our code example! after hours i give up and report that as issue. Maybe im doing something wrong, i dont know. On Browserstack i can see that make the first screenshot(screenwith: 320) but if they try to make the second one it throw an error :(

error message
===========
```shell
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: write EPIPE
    at errnoException (net.js:901:11)
    at Object.afterWrite (net.js:718:19)
```
code example
===========
```js
// init WebdriverIO
var client = require('webdriverio').remote({
    host: 'hub.browserstack.com',
    port: 80,
    user : 'userxxx',
    key: 'passxxx',
    logLevel: 'silent',
    desiredCapabilities: {
        browserName: 'chrome'
    }
})
// init WebdriverCSS
require('webdrivercss').init(client);

client
    .init()
    .url('http://cu-camper.com')
    .getTitle(function(err,title) {
        console.log(title);
    })
    .getCssProperty('#footer', 'color', function(err, color) {
        console.log(color.value);
    })
    .webdrivercss('startpage', {
        screenWidth: [320,480,640,1024],
        name: 'main-wrapper',
        elem: 'footer',
        screenshotRoot: 'src/js/tests/shots',
        failedComparisonsRoot: 'src/js/tests/diffs',
        misMatchTolerance: 0.05
    })
    .end();
```

**Comment by christian-bromann** [comment]
Is GraphicsMagick and Cairo installed properly? 

```
sudo apt-get update
sudo apt-get install graphicsmagick libcairo2-dev
```

**Comment by SerkanSipahi** [comment]
sorry, you are right ! yesterday it has worked. But today not because i have make new  setup and deleted everything. It was my false.
