### ISSUE TITLE
Error on test with remote

### ISSUE THREAD

**Issue by amitaibu** [webdriverio/webdrivercss#60]
The following test works fine on my local:

```javascript
client
  .init()
  .url('http://google.com')
  .webdrivercss('google', {name: 'homepage'})
  .end();
```

But when executed with SauceLabs or BrowserStack via [TravisCI](https://travis-ci.org/Gizra/haskala/builds/51759497#L135) I get:

```
Error: [webdrivercss("chrome",{"name":"homepage"})] <= 
 [saveDocumentScreenshot("webdrivercss/chrome.png")] <= 
 spawn ENOENT
    at errnoException (child_process.js:1011:11)
    at Process.ChildProcess._handle.onexit (child_process.js:802:34)
```

Here's the [.travis.yml](https://github.com/Gizra/haskala/blob/webdrivercss/.travis.yml) file.

What am I missing?

**Comment by amitaibu** [comment]
Sorry for this issue, I failed to add the required settings to Travis:

```
before_install:
  - sudo apt-get update > /dev/null

  # WebDriverCss required installation.
  - sudo apt-get install graphicsmagick libcairo2-dev
  - export PKG_CONFIG_PATH=/opt/X11/lib/pkgconfig
```
