### ISSUE TITLE
When providing an exclude rectangle, getting error that scrollPos not defined

### ISSUE THREAD

**Issue by psbanka** [webdriverio/webdrivercss#63]
When creating a webdrivercss test like the following:
```javascript
var cssOptions = {
    name: 'row-selection',
    elem: MAIN_VIEW,
    exclude: [{x0: 401, y0: 418, x1: 1269, y1: 583}],
    x: 1,
    y: 1,
    width: 1300,
    height: 600,
};
client
    .webdrivercss('row-selection', cssOptions, function (err, res) {
        expect(err).toBeFalsy();
        console.log(res);
        expect(res['row-selection'][0].isWithinMisMatchTolerance).toBeTruthy();
    })
    .call(done);
```

I am getting an error:
```javascript
TypeError: Cannot read property 'x' of undefined
  at Object.module.exports (/Users/pbanka/dev/cy-connections-ui/node_modules/webdrivercss/lib/cropImage.js:23:39)
  at fn (/Users/pbanka/dev/cy-connections-ui/node_modules/webdrivercss/node_modules/async/lib/async.js:582:34)
  at Object._onImmediate (/Users/pbanka/dev/cy-connections-ui/node_modules/webdrivercss/node_modules/async/lib/async.js:498:34)
  at processImmediate [as _immediateCallback] (timers.js:330:15)
```

**Comment by christian-bromann** [comment]
closing. PR got merged an will get published today

**Comment by psbanka** [comment]
Nice! Looking forward to the new version; thanks.

**Comment by christian-bromann** [comment]
@psbanka it's already published :wink:
